  [31mlabrepo/HEAD[m -> labrepo/main
  [31mlabrepo/Lab_Test_Order[m
  [31mlabrepo/NursePatientMonitoring[m
  [31mlabrepo/development[m
  [31mlabrepo/emergency_handling[m
  [31mlabrepo/feature/payroll[m
  [31mlabrepo/main[m
  [31mlabrepo/nurse_notes[m
  [31mlabrepo/pharmacy_dashboard[m
  [31mlabrepo/teamA[m
  [31mlabrepo/teamB[m
  [31mlabrepo/teamC[m
  [31morigin/Attendence[m
  [31morigin/Billing_Accountant_teamC[m
  [31morigin/HEAD[m -> origin/main
  [31morigin/HR-Report[m
  [31morigin/IPDAdmission[m
  [31morigin/Ipd_doctor_teamC[m
  [31morigin/LabView_teamC[m
  [31morigin/Lab_Test_Order[m
  [31morigin/NurseDashboard_teamC[m
  [31morigin/NursePatientMonitoring[m
  [31morigin/NurseReport_teamC[m
  [31morigin/Payment_Accountant_teamC[m
  [31morigin/deduction-rule-set[m
  [31morigin/development[m
  [31morigin/dischargePrep_teamC[m
  [31morigin/emergency_handling[m
  [31morigin/employee-salary-assignment-teamA[m
  [31morigin/equipment[m
  [31morigin/expense_management_v2[m
  [31morigin/feature/payroll[m
  [31morigin/financial-reconcilation[m
  [31morigin/insurance-claim_Accountant[m
  [31morigin/insurance_teamC[m
  [31morigin/main[m
  [31morigin/nurse-shifts[m
  [31morigin/nurse_notes[m
  [31morigin/payroll-dashboard[m
  [31morigin/payroll-deduction-breakdown-teamA[m
  [31morigin/payroll-earnings-breakdown-teamA[m
  [31morigin/payrollResult_teamA[m
  [31morigin/payroll_result_module14_teamA[m
  [31morigin/pharmacy_dashboard[m
  [31morigin/pharmacyreport[m
  [31morigin/pre-payroll-adjustment-teamA[m
  [31morigin/rateEmployeeMapping_teamA[m
  [31morigin/receptionist_billing_teamC[m
  [31morigin/receptionist_reports_teamC[m
  [31morigin/receptionistdashboard_teamC[m
  [31morigin/revenue-management[m
  [31morigin/salary-structure[m
  [31morigin/statutory-deduction-teamA[m
  [31morigin/statutoryContribution_teamA[m
  [31morigin/teamA[m
  [31morigin/teamB[m
  [31morigin/teamC[m
